import type { Metadata } from "next";
import "./globals.css";
import { NavigationMenuDemo } from "@/Componenets/ui/navbar";
import { Exo } from "next/font/google";
import ToastProvider from "@/Componenets/ui/Toastify";
const exoSans = Exo({
  subsets: ["latin"],
  variable: "--font-exo-sans",
});

const exoMono = Exo({
  subsets: ["latin"],
  variable: "--font-exo-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exoSans.variable} ${exoMono.variable} antialiased`}>
        <NavigationMenuDemo />
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
